export enum LearningAnalyticsDashboardEvents {
  GENERIC_DATA_SENT = 'GENERIC_DATA_FOR_LEARNING_ANALYTICS_DASHBOARD_SENT',
  UPSERT_DATA_COMMAND_SENT = 'UPSERT_DATA_COMMAND_FOR_LEARNING_ANALYTICS_DASHBOARD_SENT',
  DELETE_DATA_COMMAND_SENT = 'DELETE_DATA_COMMAND_FOR_LEARNING_ANALYTICS_DASHBOARD_SENT',
}
