export enum LearningAnalyticsDashboardEvents {
  GENERIC_DATA_SENT = 'GENERIC_DATA_FOR_LEARNING_ANALYTICS_DASHBOARD_SENT',
  UPSERT_GENERIC_DATA_SENT = 'UPSERT_GENERIC_DATA_FOR_LEARNING_ANALYTICS_DASHBOARD_SENT',
  DELETE_GENERIC_DATA_SENT = 'DELETE_GENERIC_DATA_FOR_LEARNING_ANALYTICS_DASHBOARD_SENT',
}
