name: Build and Release

on: [pull_request]

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Package build into tar.gz
        run: |
          mkdir -p build
          cp -r dist/ build/
          tar -czf bigbluebutton-html-plugin-sdk.tar.gz -C build .

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: bigbluebutton-html-plugin-sdk.tar.gz