name: Samples Code Validation (Typescript and ESLINT)
on: [pull_request]
permissions:
  contents: read
jobs:
  ts-code-compilation:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Merge branches
        uses: ./.github/actions/merge-branches
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install SDK dependencies
        run: npm ci
      - name: Build SDK
        run: npm run build
      - name: Validate Samples code with current SDK
        run: ./scripts/validate-samples-code.sh
