name: Typescript - validate code (eslint)
on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
jobs:
  ts-code-validation:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Merge branches
        uses: ./.github/actions/merge-branches
      - name: run npm install
        run: npm install
      - name: typescript code validation with eslint
        run: npx eslint
